//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalkulator.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaObliczen
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Dzialanie { get; set; }
        public string PierwszaWartosc { get; set; }
        public string DrugaWartosc { get; set; }
        public string WartoscPo { get; set; }
    }
}
