//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountCreator2.Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountCreatorEntities : DbContext
    {
        public AccountCreatorEntities()
            : base("name=AccountCreatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountsAlreadyMade> AccountsAlreadyMade { get; set; }
        public virtual DbSet<Usernames> Usernames { get; set; }
        public virtual DbSet<ocenaTable> ocenaTable { get; set; }
    }
}
