//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int ID { get; set; }
        public string Vehicle_type { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Vehicle_class { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
