//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwerter.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaKonwerter
    {
        public int ID { get; set; }
        public string RodzajKonwertera { get; set; }
        public string Jednostka_IN { get; set; }
        public string Jednostka_OUT { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Liczba_IN { get; set; }
        public string Liczba_OUT { get; set; }
        public Nullable<int> Ocena { get; set; }
    }
}
