//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class dane
    {
        public int id { get; set; }
        public string konwerter { get; set; }
        public System.DateTime data { get; set; }
        public double wejscie { get; set; }
        public double wyjscie { get; set; }
    }
}
