//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Converter
    {
        public int ID { get; set; }
        public string ConverterName { get; set; }
        public string ConversionFrom { get; set; }
        public string ConversionTo { get; set; }
        public System.DateTime ConversionDate { get; set; }
    }
}
