//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przeliczniki.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przeliczenia
    {
        public int id { get; set; }
        public string konwerter { get; set; }
        public double wartosc { get; set; }
        public System.DateTime data { get; set; }
        public string jednostkaZ { get; set; }
        public string jednostkaDo { get; set; }
        public double wynik { get; set; }
    }
}
