//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwerter.Desctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Id { get; set; }
        public string converter_type { get; set; }
        public string unit_from { get; set; }
        public string unit_to { get; set; }
        public System.DateTime conversion_data { get; set; }
        public string insert_data { get; set; }
        public string output_data { get; set; }
    }
}
