//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bryly
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrylaTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Input { get; set; }
        public string Result { get; set; }
    }
}
