// <auto-generated />
namespace UnitConverterv2.Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class uniDBSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniDBSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "202009172014519_uniDB Schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
