//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ziecinaUnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIPP4
    {
        public int ID { get; set; }
        public string Converter { get; set; }
        public string unitFrom { get; set; }
        public string unitTo { get; set; }
        public string valueBefore { get; set; }
        public string valueAfter { get; set; }
        public Nullable<bool> errorEncountered { get; set; }
        public Nullable<System.DateTime> dateSent { get; set; }
    }
}
