//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabelaa
    {
        public int ID { get; set; }
        public string Converter { get; set; }
        public string ConverterTo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string wartosc { get; set; }
        public string wartoscdo { get; set; }
        public string nazwa { get; set; }
    }
}
