//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BazaDanych
    {
        public int Id { get; set; }
        public string Konwertor { get; set; }
        public string Z { get; set; }
        public string Do { get; set; }
        public string WartoscWejsciowa { get; set; }
        public string WartoscWyjsciowa { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
