//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConverterRecord
    {
        public int ID { get; set; }
        public string NameConverter { get; set; }
        public string UnitFrom { get; set; }
        public string UnitTo { get; set; }
        public decimal Value { get; set; }
        public decimal Result { get; set; }
        public Nullable<System.DateTime> DateRecord { get; set; }
    }
}
