//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTIC
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> VALUEFROM { get; set; }
        public Nullable<double> VALUETO { get; set; }
        public string UNITFROM { get; set; }
        public string UNITTO { get; set; }
    }
}
