//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pola_figur.desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kistoria_Obliczen
    {
        public int ID { get; set; }
        public System.DateTime Data { get; set; }
        public string Figura { get; set; }
        public string Obliczanie { get; set; }
        public decimal Wartosc { get; set; }
        public decimal Wynik { get; set; }
    }
}
