//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitKonwerter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionHistory
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Converter { get; set; }
        public string UnitFrom { get; set; }
        public string UnitTo { get; set; }
        public string ValueBefore { get; set; }
        public string ValueAfter { get; set; }
    }
}
