//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversion
    {
        public int id { get; set; }
        public string converter { get; set; }
        public decimal input_value { get; set; }
        public string input_unit { get; set; }
        public decimal output_value { get; set; }
        public string output_unit { get; set; }
        public System.DateTime date { get; set; }
    }
}
