//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapissql
    {
        public int id { get; set; }
        public string converter { get; set; }
        public string unitfrom { get; set; }
        public string unitto { get; set; }
        public Nullable<decimal> inputvalue { get; set; }
        public string outputvalue { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
