//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int id { get; set; }
        public double valueOne { get; set; }
        public double valueTwo { get; set; }
        public string operation1 { get; set; }
        public double result { get; set; }
    }
}
