//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string FromUnit { get; set; }
        public string ToUnit { get; set; }
        public Nullable<System.DateTime> ConvertHour { get; set; }
        public double Value { get; set; }
        public double Result { get; set; }
    }
}
