//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reviewer.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public string TITLE { get; set; }
        public string TYPE { get; set; }
        public string SCORE { get; set; }
        public string DESCRIPTION { get; set; }
        public string RELEASE_DATE { get; set; }
    }
}
