//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonwerterJednostek2.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string Typ { get; set; }
        public string JednostkaZ { get; set; }
        public string JednostkaDo { get; set; }
        public System.DateTime Data { get; set; }
        public string WartoscPrzed { get; set; }
        public string WartoscPo { get; set; }
    }
}
