//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int Id { get; set; }
        public string converter { get; set; }
        public string unitIn { get; set; }
        public string unitOut { get; set; }
        public Nullable<System.DateTime> ConversionDate { get; set; }
        public string valueIn { get; set; }
        public string valueOut { get; set; }
    }
}
