//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;

namespace KonwerterJednostek.Logic
{
    public class DatabaseService
    {
        public static void InsertDataUsingEF(string type, string fr, string to, DateTime dt, decimal vl, decimal cvl)
        {
            using (statystykiEntities1 entities1 = new statystykiEntities1())
            {
                stats statystyki = new stats()
                {
                    convType = type,
                    unitFrom = fr,
                    unitTo = to,
                    convDate = dt,
                    convValue = vl,
                    convertedValue = cvl
                };
                entities1.stats.Add(statystyki);
                entities1.SaveChanges();
            }
        }

        public static void InsertRateUsingEF(int val)
        {
            statystykiEntities1 db = new statystykiEntities1();
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE rate");
            using (statystykiEntities1 entities1 = new statystykiEntities1())
            {
                rate r = new rate()
                {
                    rateValue = val
                };
                entities1.rate.Add(r);
                entities1.SaveChanges();
            }
        }
    }
}
