//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonwerterJednostek.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats
    {
        public int ID { get; set; }
        public string convType { get; set; }
        public string unitFrom { get; set; }
        public string unitTo { get; set; }
        public Nullable<System.DateTime> convDate { get; set; }
        public Nullable<decimal> convValue { get; set; }
        public Nullable<decimal> convertedValue { get; set; }
    }
}
