//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konwerter.deskop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BazaOcena
    {
        public int idocena { get; set; }
        public int ocena { get; set; }
    }
}
