//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konwerter.deskop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baza001
    {
        public int id { get; set; }
        public string converter { get; set; }
        public string unitFrom { get; set; }
        public string unitTo { get; set; }
        public decimal inputValue { get; set; }
        public string outputValue { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
