//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonwerterKonsolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVERSIONS
    {
        public int rowId { get; set; }
        public string name { get; set; }
        public string unitFrom { get; set; }
        public string unitTo { get; set; }
        public System.DateTime dateOfConversion { get; set; }
        public decimal valueToConvert { get; set; }
        public decimal valueAfterConvert { get; set; }
    }
}
