// <auto-generated />
namespace Zadanie_7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracja20082020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracja20082020));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201701292_migracja20-08-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
