//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flower : IRow
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int RoomID { get; set; }
        public System.DateTime LastWatered { get; set; }
        public int WateredFrequency { get; set; }
    }
}
