//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonwerterJednostekLK.DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConverterDB
    {
        public int Id { get; set; }
        public string ConverterName { get; set; }
        public System.DateTime ConversionDate { get; set; }
    }
}
