//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public double Value { get; set; }
        public double Capacity { get; set; }
        public Nullable<byte> Quantity { get; set; }
    }
}
