//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwenter_jednostek.DESKTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dane
    {
        public int id { get; set; }
        public string rodzaj { get; set; }
        public string jednostki { get; set; }
        public System.DateTime data_konwersji { get; set; }
        public double wartosc_konwertowana { get; set; }
        public double wartosc_przekonwertowana { get; set; }
    }
}
