//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonwerterJednostek.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaWynikow
    {
        public int ID { get; set; }
        public string TYP { get; set; }
        public string Jednostka_przed { get; set; }
        public string Jednostka_po { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Wartosc_przed { get; set; }
        public string Wartosc_po { get; set; }
    }
}
