//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwerter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konwert_History
    {
        public int ID { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Wartosc_z { get; set; }
        public string Jednostka_z { get; set; }
        public decimal Wartosc_do { get; set; }
        public string Jednostka_do { get; set; }
    }
}
