//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwerter.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_History
    {
        public int IDRate { get; set; }
        public int RateValue { get; set; }
    }
}
