//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocena
    {
        public int ID { get; set; }
        public int Oceny { get; set; }
    }
}
