//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stata
    {
        public int ID { get; set; }
        public string Rodzaj_Konwertera { get; set; }
        public string Wybrana_jednostka { get; set; }
        public System.DateTime Data_Konwersji { get; set; }
        public decimal Wartosc_podana { get; set; }
        public decimal Wartosc_uzyskana { get; set; }
    }
}
