//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontakty.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int Id { get; set; }
        public string Nazwisko { get; set; }
        public string Kontakt { get; set; }
        public string NazwaTypu { get; set; }
        public int NumerTypu { get; set; }
    }
}
