//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class statystyki
    {
        public int id { get; set; }
        public string Rodzaj { get; set; }
        public string Jednostki { get; set; }
        public System.DateTime Data { get; set; }
        public string WartoscPrzed { get; set; }
        public string WartoscPo { get; set; }
    }
}
