//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadanie_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class komputer
    {
        public int idkompa { get; set; }
        public string nazwa_komputera { get; set; }
        public string numer_seryjny { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
