//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiPP_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uczen
    {
        public int ID { get; set; }
        public string Przedmiot { get; set; }
        public Nullable<int> Ocena { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
