//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwerter.Okienko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bananas
    {
        public int numer { get; set; }
        public string rodzaj { get; set; }
        public string jednostki { get; set; }
        public System.DateTime data { get; set; }
        public string wartosc { get; set; }
        public string wynik { get; set; }
    }
}
